name: fateen
description: "A new Flutter project with Firebase integration."

# منع نشر الحزمة إلى pub.dev
publish_to: 'none'

# إصدار التطبيق
version: 1.0.0+1

# بيئة المشروع
environment:
  sdk: ">=3.5.0 <4.0.0"

# الحزم المطلوبة لتشغيل التطبيق
dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0

  # الحزمة الخاصة بأيقونات iOS
  cupertino_icons: ^1.0.8

  # خطوط Google
  google_fonts: ^5.0.0

# الحزم الخاصة بتطوير التطبيق
dev_dependencies:
  flutter_test:
    sdk: flutter

  # قواعد البرمجة الجيدة
  flutter_lints: ^4.0.0

# إعدادات Flutter
flutter:
  uses-material-design: true

  # الأصول (assets) مثل الصور والخطوط
  assets:
    - assets/images/

  # الخطوط المخصصة
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700